### ISSUE TITLE
question: why is the resistor needed in wiring the Gasmeter

### ISSUE THREAD

**Issue by rainersax** [zibous/ha-gasmeter#1]
Hi,
I am trying to recreate the setup you habe for your gasmeter.
You describe the wiring like this in gasmeter.yaml 119-121:

```
# GASCOUNTER ZI-61 REED CONTACT
# GPIO19 <-- o-RC-o <--- GND
#            o-10k ----> +5V
```

Why do you need the 10k resistor? 

### Assumption:
as GPIO19 is in pull-up mode there is voltage on the pin. When the reed contact closes the current goes to ground and the pin is DOWN. When the reed contact is open the pin is UP.

### Question:
Why do you need the resistor attached to a +5V pin? Can't this be left out?
Thanks for your help and most of all for building it in the first place. 
cheers, 
Rainer

**Comment by zibous** [comment]
Resistor is not necessarily needed,  because the GIPO19 has internal resistor. 
But when I took my measurements, I received better signals with a resistor.
