### ISSUE TITLE
Other sensor from ELV (ES-GAS-2)

### ISSUE THREAD

**Issue by schadom** [zibous/ha-gasmeter#2]
Hello,

I have the newer but identical Elster BK-G2,5M gas meter from VKW.  I have planned to use the following sensors from ELV: https://de.elv.com/elv-energy-sensor-gas-2-es-gas-2-156782

Do you maybe know if this should also work?

Thanks

**Comment by zibous** [comment]
Hi,

The ES-Gas-2 can only be used on counters that are equipped with a magnet. 
It cannot be used on counters with a cyble target.
A cyble sensor is required, the output of which provides a reed contact equivalent. 

You just have to find out which of the connections provide the signal from the read contact. 
For me it didn't work with the first gas meter because there was no  magnet encoder installed there. 

It is easier with a simple read contact and an ESP, which costs only a few cents.

**Comment by schadom** [comment]
Thank you very much for the info! I will try it out with a reed contact and an ESP32 :)

**Comment by schadom** [comment]
Short update - unfortunately it's not working with my BK-G2,5 M gas meter and the ES-GAS-2 sensor. Seems my gas meter is lacking a magnet as well. The reed contact of the ES-GAS-2 sensor works fine if I get close with a magnet, so it is not a problem with the sensor. Here is a image from my meter:

[![gas.jpg](https://i.postimg.cc/zD2QqK1S/gas.jpg)](https://postimg.cc/0rmnf6jb)

According to the manual from Elster/Honeywell, there are three different counter versions (M = Mechanisches Zählwerk, A = Absolut ENCODER Zählwerk, T = Mechanisch) in the BK-Gx series. Additionally the manual also states that all pulse transmitters from the IN-Z6x are compatible. From my understanding, the IN-Z6x pulse transmitters are based on a reed contact too, so I assume this won't work either? Or is there any difference with those IN-Z6x sensors compared to the ES-GAS-2 sensor? Thanks

**Comment by zibous** [comment]
@schadom 

> From my understanding, the IN-Z6x pulse transmitters are based on a reed contact too, so I assume this won't work either? 
YES it is a simple  reed contact sensor.

You must first find out if the gas meter has a magnet. This is attached to the last position of the counter.

Simple check:
- Take an old compass and see if the needle deflects.
- Or a cell phone with a compass app
- Or a simple Zigbee, WLAN door sensor, Lidl had one on offer.

Or simply an ESP8266 / ESP32 with a reed contact and an LED. If the LED shows when you move a magnet over the reed contact, then the circuit is working.

![Bildschirmfoto 2022-11-13 um 12 41 05](https://user-images.githubusercontent.com/30198737/201519987-aac51f2b-ea1b-449e-ac1e-68d60d7d6540.png)

If the gas meter doesn't have magnets, which is unlikely with this version, then you'll need to have the gas meter replaced, but it's not that easy.

You can also contact me directly via email:
https://peter.siebler.at/contact/
